# Auto-generated basic equipment data for 5e SRD/Basic Rules.
WEAPONS = [{'cost': '1 sp',
  'name': 'Club',
  'props': {'weapon': {'category': 'simple',
                       'damage': '1d4 bludgeoning',
                       'properties': ['light', 'monk'],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 2},
 {'cost': '2 gp',
  'name': 'Dagger',
  'props': {'weapon': {'category': 'simple',
                       'damage': '1d4 piercing',
                       'properties': ['finesse', 'light', 'thrown', 'monk'],
                       'range': '20/60',
                       'type': 'melee'}},
  'weight': 1},
 {'cost': '2 sp',
  'name': 'Greatclub',
  'props': {'weapon': {'category': 'simple',
                       'damage': '1d8 bludgeoning',
                       'properties': ['two-handed'],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 10},
 {'cost': '5 gp',
  'name': 'Handaxe',
  'props': {'weapon': {'category': 'simple',
                       'damage': '1d6 slashing',
                       'properties': ['light', 'thrown', 'monk'],
                       'range': '20/60',
                       'type': 'melee'}},
  'weight': 2},
 {'cost': '5 sp',
  'name': 'Javelin',
  'props': {'weapon': {'category': 'simple',
                       'damage': '1d6 piercing',
                       'properties': ['thrown', 'monk'],
                       'range': '30/120',
                       'type': 'melee'}},
  'weight': 2},
 {'cost': '2 gp',
  'name': 'Light hammer',
  'props': {'weapon': {'category': 'simple',
                       'damage': '1d4 bludgeoning',
                       'properties': ['light', 'thrown', 'monk'],
                       'range': '20/60',
                       'type': 'melee'}},
  'weight': 2},
 {'cost': '5 gp',
  'name': 'Mace',
  'props': {'weapon': {'category': 'simple',
                       'damage': '1d6 bludgeoning',
                       'properties': ['monk'],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 4},
 {'cost': '2 sp',
  'name': 'Quarterstaff',
  'props': {'weapon': {'category': 'simple',
                       'damage': '1d6 bludgeoning',
                       'properties': ['versatile', 'monk'],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 4},
 {'cost': '1 gp',
  'name': 'Sickle',
  'props': {'weapon': {'category': 'simple',
                       'damage': '1d4 slashing',
                       'properties': ['light', 'monk'],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 2},
 {'cost': '1 gp',
  'name': 'Spear',
  'props': {'weapon': {'category': 'simple',
                       'damage': '1d6 piercing',
                       'properties': ['thrown', 'versatile', 'monk'],
                       'range': '20/60',
                       'type': 'melee'}},
  'weight': 3},
 {'cost': '25 gp',
  'name': 'Crossbow, light',
  'props': {'weapon': {'category': 'simple',
                       'damage': '1d8 piercing',
                       'properties': ['ammunition', 'loading', 'two-handed'],
                       'range': '80/320',
                       'type': 'ranged'}},
  'weight': 5},
 {'cost': '5 cp',
  'name': 'Dart',
  'props': {'weapon': {'category': 'simple',
                       'damage': '1d4 piercing',
                       'properties': ['finesse', 'thrown'],
                       'range': '20/60',
                       'type': 'ranged'}},
  'weight': 0.25},
 {'cost': '25 gp',
  'name': 'Shortbow',
  'props': {'weapon': {'category': 'simple',
                       'damage': '1d6 piercing',
                       'properties': ['ammunition', 'two-handed'],
                       'range': '80/320',
                       'type': 'ranged'}},
  'weight': 2},
 {'cost': '1 sp',
  'name': 'Sling',
  'props': {'weapon': {'category': 'simple',
                       'damage': '1d4 bludgeoning',
                       'properties': ['ammunition'],
                       'range': '30/120',
                       'type': 'ranged'}},
  'weight': 0},
 {'cost': '10 gp',
  'name': 'Battleaxe',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1d8 slashing',
                       'properties': ['versatile'],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 4},
 {'cost': '10 gp',
  'name': 'Flail',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1d8 bludgeoning',
                       'properties': [],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 2},
 {'cost': '20 gp',
  'name': 'Glaive',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1d10 slashing',
                       'properties': ['heavy', 'reach', 'two-handed'],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 6},
 {'cost': '30 gp',
  'name': 'Greataxe',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1d12 slashing',
                       'properties': ['heavy', 'two-handed'],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 7},
 {'cost': '50 gp',
  'name': 'Greatsword',
  'props': {'weapon': {'category': 'martial',
                       'damage': '2d6 slashing',
                       'properties': ['heavy', 'two-handed'],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 6},
 {'cost': '20 gp',
  'name': 'Halberd',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1d10 slashing',
                       'properties': ['heavy', 'reach', 'two-handed'],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 6},
 {'cost': '10 gp',
  'name': 'Lance',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1d12 piercing',
                       'properties': ['reach', 'special'],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 6},
 {'cost': '15 gp',
  'name': 'Longsword',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1d8 slashing',
                       'properties': ['versatile'],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 3},
 {'cost': '10 gp',
  'name': 'Maul',
  'props': {'weapon': {'category': 'martial',
                       'damage': '2d6 bludgeoning',
                       'properties': ['heavy', 'two-handed'],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 10},
 {'cost': '15 gp',
  'name': 'Morningstar',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1d8 piercing',
                       'properties': [],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 4},
 {'cost': '5 gp',
  'name': 'Pike',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1d10 piercing',
                       'properties': ['heavy', 'reach', 'two-handed'],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 18},
 {'cost': '25 gp',
  'name': 'Rapier',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1d8 piercing',
                       'properties': ['finesse'],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 2},
 {'cost': '25 gp',
  'name': 'Scimitar',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1d6 slashing',
                       'properties': ['finesse', 'light'],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 3},
 {'cost': '10 gp',
  'name': 'Shortsword',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1d6 piercing',
                       'properties': ['finesse', 'light', 'monk'],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 2},
 {'cost': '5 gp',
  'name': 'Trident',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1d6 piercing',
                       'properties': ['thrown', 'versatile'],
                       'range': '20/60',
                       'type': 'melee'}},
  'weight': 4},
 {'cost': '5 gp',
  'name': 'War pick',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1d8 piercing',
                       'properties': [],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 2},
 {'cost': '15 gp',
  'name': 'Warhammer',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1d8 bludgeoning',
                       'properties': ['versatile'],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 2},
 {'cost': '2 gp',
  'name': 'Whip',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1d4 slashing',
                       'properties': ['finesse', 'reach'],
                       'range': '5',
                       'type': 'melee'}},
  'weight': 3},
 {'cost': '10 gp',
  'name': 'Blowgun',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1 piercing',
                       'properties': ['ammunition', 'loading'],
                       'range': '25/100',
                       'type': 'ranged'}},
  'weight': 1},
 {'cost': '75 gp',
  'name': 'Crossbow, hand',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1d6 piercing',
                       'properties': ['ammunition', 'light', 'loading'],
                       'range': '30/120',
                       'type': 'ranged'}},
  'weight': 3},
 {'cost': '50 gp',
  'name': 'Crossbow, heavy',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1d10 piercing',
                       'properties': ['ammunition', 'heavy', 'loading', 'two-handed'],
                       'range': '100/400',
                       'type': 'ranged'}},
  'weight': 18},
 {'cost': '50 gp',
  'name': 'Longbow',
  'props': {'weapon': {'category': 'martial',
                       'damage': '1d8 piercing',
                       'properties': ['ammunition', 'heavy', 'two-handed'],
                       'range': '150/600',
                       'type': 'ranged'}},
  'weight': 2},
 {'cost': '1 gp',
  'name': 'Net',
  'props': {'weapon': {'category': 'martial',
                       'damage': None,
                       'properties': ['thrown', 'special'],
                       'range': '5/15',
                       'type': 'ranged'}},
  'weight': 3}]

ARMOR = [{'cost': '5 gp',
  'name': 'Padded Armor',
  'props': {'armor': {'base': 11, 'category': 'light', 'dex_cap': None}, 'stealth_disadvantage': True},
  'weight': 8},
 {'cost': '10 gp',
  'name': 'Leather Armor',
  'props': {'armor': {'base': 11, 'category': 'light', 'dex_cap': None}},
  'weight': 10},
 {'cost': '45 gp',
  'name': 'Studded Leather Armor',
  'props': {'armor': {'base': 12, 'category': 'light', 'dex_cap': None}},
  'weight': 13},
 {'cost': '10 gp',
  'name': 'Hide Armor',
  'props': {'armor': {'base': 12, 'category': 'medium', 'dex_cap': 2}},
  'weight': 12},
 {'cost': '50 gp',
  'name': 'Chain Shirt',
  'props': {'armor': {'base': 13, 'category': 'medium', 'dex_cap': 2}},
  'weight': 20},
 {'cost': '50 gp',
  'name': 'Scale Mail',
  'props': {'armor': {'base': 14, 'category': 'medium', 'dex_cap': 2}, 'stealth_disadvantage': True},
  'weight': 45},
 {'cost': '400 gp',
  'name': 'Breastplate',
  'props': {'armor': {'base': 14, 'category': 'medium', 'dex_cap': 2}},
  'weight': 20},
 {'cost': '750 gp',
  'name': 'Half Plate Armor',
  'props': {'armor': {'base': 15, 'category': 'medium', 'dex_cap': 2}, 'stealth_disadvantage': True},
  'weight': 40},
 {'cost': '30 gp',
  'name': 'Ring Mail',
  'props': {'armor': {'base': 14, 'category': 'heavy', 'dex_cap': 0}, 'stealth_disadvantage': True},
  'weight': 40},
 {'cost': '75 gp',
  'name': 'Chain Mail',
  'props': {'armor': {'base': 16, 'category': 'heavy', 'dex_cap': 0},
            'stealth_disadvantage': True,
            'strength_requirement': 13},
  'weight': 55},
 {'cost': '200 gp',
  'name': 'Splint Armor',
  'props': {'armor': {'base': 17, 'category': 'heavy', 'dex_cap': 0},
            'stealth_disadvantage': True,
            'strength_requirement': 15},
  'weight': 60},
 {'cost': '1500 gp',
  'name': 'Plate Armor',
  'props': {'armor': {'base': 18, 'category': 'heavy', 'dex_cap': 0},
            'stealth_disadvantage': True,
            'strength_requirement': 15},
  'weight': 65}]

SHIELDS = [{'cost': '10 gp', 'name': 'Shield', 'props': {'shield_bonus': 2}, 'weight': 6}]

GEAR = [{'cost': '2 gp', 'name': 'Abacus', 'props': {}, 'weight': 2},
 {'cost': '25 gp', 'name': 'Acid (vial)', 'props': {}, 'weight': 1},
 {'cost': '50 gp', 'name': "Alchemist's fire (flask)", 'props': {}, 'weight': 1},
 {'cost': '0 cp', 'name': 'Alms box', 'props': {}, 'weight': 0},
 {'cost': '1 gp', 'name': 'Arrow', 'props': {}, 'weight': 1},
 {'cost': '0 cp', 'name': 'Block of incense', 'props': {}, 'weight': 0},
 {'cost': '1 gp', 'name': 'Blowgun needle', 'props': {}, 'weight': 1},
 {'cost': '0 cp', 'name': 'Censer', 'props': {}, 'weight': 0},
 {'cost': '1 gp', 'name': 'Crossbow bolt', 'props': {}, 'weight': 1.5},
 {'cost': '4 cp', 'name': 'Sling bullet', 'props': {}, 'weight': 1.5},
 {'cost': '5 gp', 'name': 'Amulet', 'props': {}, 'weight': 1},
 {'cost': '50 gp', 'name': 'Antitoxin (vial)', 'props': {}, 'weight': 0},
 {'cost': '10 gp', 'name': 'Crystal', 'props': {}, 'weight': 1},
 {'cost': '20 gp', 'name': 'Orb', 'props': {}, 'weight': 3},
 {'cost': '10 gp', 'name': 'Rod', 'props': {}, 'weight': 2},
 {'cost': '5 gp', 'name': 'Staff', 'props': {}, 'weight': 4},
 {'cost': '10 gp', 'name': 'Wand', 'props': {}, 'weight': 1},
 {'cost': '2 gp', 'name': 'Backpack', 'props': {}, 'weight': 5},
 {'cost': '1 gp', 'name': 'Ball bearings (bag of 1,000)', 'props': {}, 'weight': 2},
 {'cost': '2 gp', 'name': 'Barrel', 'props': {}, 'weight': 70},
 {'cost': '4 sp', 'name': 'Basket', 'props': {}, 'weight': 2},
 {'cost': '1 gp', 'name': 'Bedroll', 'props': {}, 'weight': 7},
 {'cost': '1 gp', 'name': 'Bell', 'props': {}, 'weight': 0},
 {'cost': '5 sp', 'name': 'Blanket', 'props': {}, 'weight': 3},
 {'cost': '1 gp', 'name': 'Block and tackle', 'props': {}, 'weight': 5},
 {'cost': '25 gp', 'name': 'Book', 'props': {}, 'weight': 5},
 {'cost': '2 gp', 'name': 'Bottle, glass', 'props': {}, 'weight': 2},
 {'cost': '5 cp', 'name': 'Bucket', 'props': {}, 'weight': 2},
 {'cost': '5 cp', 'name': 'Caltrops', 'props': {}, 'weight': 2},
 {'cost': '1 cp', 'name': 'Candle', 'props': {}, 'weight': 0},
 {'cost': '1 gp', 'name': 'Case, crossbow bolt', 'props': {}, 'weight': 1},
 {'cost': '1 gp', 'name': 'Case, map or scroll', 'props': {}, 'weight': 1},
 {'cost': '5 gp', 'name': 'Chain (10 feet)', 'props': {}, 'weight': 10},
 {'cost': '1 cp', 'name': 'Chalk (1 piece)', 'props': {}, 'weight': 0},
 {'cost': '5 gp', 'name': 'Chest', 'props': {}, 'weight': 25},
 {'cost': '5 sp', 'name': 'Clothes, common', 'props': {}, 'weight': 3},
 {'cost': '5 gp', 'name': 'Clothes, costume', 'props': {}, 'weight': 4},
 {'cost': '15 gp', 'name': 'Clothes, fine', 'props': {}, 'weight': 6},
 {'cost': '2 gp', 'name': "Clothes, traveler's", 'props': {}, 'weight': 4},
 {'cost': '25 gp', 'name': 'Component pouch', 'props': {}, 'weight': 2},
 {'cost': '2 gp', 'name': 'Crowbar', 'props': {}, 'weight': 5},
 {'cost': '1 gp', 'name': 'Sprig of mistletoe', 'props': {}, 'weight': 0},
 {'cost': '1 gp', 'name': 'Totem', 'props': {}, 'weight': 0},
 {'cost': '5 gp', 'name': 'Wooden staff', 'props': {}, 'weight': 4},
 {'cost': '10 gp', 'name': 'Yew wand', 'props': {}, 'weight': 1},
 {'cost': '5 gp', 'name': 'Emblem', 'props': {}, 'weight': 0},
 {'cost': '1 gp', 'name': 'Fishing tackle', 'props': {}, 'weight': 4},
 {'cost': '2 cp', 'name': 'Flask or tankard', 'props': {}, 'weight': 1},
 {'cost': '2 gp', 'name': 'Grappling hook', 'props': {}, 'weight': 4},
 {'cost': '1 gp', 'name': 'Hammer', 'props': {}, 'weight': 3},
 {'cost': '2 gp', 'name': 'Hammer, sledge', 'props': {}, 'weight': 10},
 {'cost': '25 gp', 'name': 'Holy water (flask)', 'props': {}, 'weight': 1},
 {'cost': '25 gp', 'name': 'Hourglass', 'props': {}, 'weight': 1},
 {'cost': '5 gp', 'name': 'Hunting trap', 'props': {}, 'weight': 25},
 {'cost': '10 gp', 'name': 'Ink (1 ounce bottle)', 'props': {}, 'weight': 0},
 {'cost': '2 cp', 'name': 'Ink pen', 'props': {}, 'weight': 0},
 {'cost': '2 cp', 'name': 'Jug or pitcher', 'props': {}, 'weight': 4},
 {'cost': '25 gp', 'name': "Climber's Kit", 'props': {}, 'weight': 12},
 {'cost': '25 gp', 'name': 'Disguise Kit', 'props': {}, 'weight': 3},
 {'cost': '15 gp', 'name': 'Forgery Kit', 'props': {}, 'weight': 5},
 {'cost': '5 gp', 'name': 'Herbalism Kit', 'props': {}, 'weight': 3},
 {'cost': '5 gp', 'name': "Healer's Kit", 'props': {}, 'weight': 3},
 {'cost': '2 sp', 'name': 'Mess Kit', 'props': {}, 'weight': 1},
 {'cost': '50 gp', 'name': "Poisoner's Kit", 'props': {}, 'weight': 2},
 {'cost': '1 sp', 'name': 'Ladder (10-foot)', 'props': {}, 'weight': 25},
 {'cost': '5 sp', 'name': 'Lamp', 'props': {}, 'weight': 1},
 {'cost': '10 gp', 'name': 'Lantern, bullseye', 'props': {}, 'weight': 2},
 {'cost': '5 gp', 'name': 'Lantern, hooded', 'props': {}, 'weight': 2},
 {'cost': '0 cp', 'name': 'Little bag of sand', 'props': {}, 'weight': 0},
 {'cost': '10 gp', 'name': 'Lock', 'props': {}, 'weight': 1},
 {'cost': '100 gp', 'name': 'Magnifying glass', 'props': {}, 'weight': 0},
 {'cost': '2 gp', 'name': 'Manacles', 'props': {}, 'weight': 6},
 {'cost': '5 gp', 'name': 'Mirror, steel', 'props': {}, 'weight': 0.5},
 {'cost': '1 sp', 'name': 'Oil (flask)', 'props': {}, 'weight': 1},
 {'cost': '2 sp', 'name': 'Paper (one sheet)', 'props': {}, 'weight': 0},
 {'cost': '1 sp', 'name': 'Parchment (one sheet)', 'props': {}, 'weight': 0},
 {'cost': '5 gp', 'name': 'Perfume (vial)', 'props': {}, 'weight': 0},
 {'cost': '2 gp', 'name': "Pick, miner's", 'props': {}, 'weight': 10},
 {'cost': '5 cp', 'name': 'Piton', 'props': {}, 'weight': 0.25},
 {'cost': '100 gp', 'name': 'Poison, basic (vial)', 'props': {}, 'weight': 0},
 {'cost': '5 cp', 'name': 'Pole (10-foot)', 'props': {}, 'weight': 7},
 {'cost': '2 gp', 'name': 'Pot, iron', 'props': {}, 'weight': 10},
 {'cost': '5 sp', 'name': 'Pouch', 'props': {}, 'weight': 1},
 {'cost': '1 gp', 'name': 'Quiver', 'props': {}, 'weight': 1},
 {'cost': '4 gp', 'name': 'Ram, portable', 'props': {}, 'weight': 35},
 {'cost': '5 sp', 'name': 'Rations (1 day)', 'props': {}, 'weight': 2},
 {'cost': '5 gp', 'name': 'Reliquary', 'props': {}, 'weight': 2},
 {'cost': '1 gp', 'name': 'Robes', 'props': {}, 'weight': 4},
 {'cost': '1 gp', 'name': 'Rope, hempen (50 feet)', 'props': {}, 'weight': 10},
 {'cost': '10 gp', 'name': 'Rope, silk (50 feet)', 'props': {}, 'weight': 5},
 {'cost': '1 cp', 'name': 'Sack', 'props': {}, 'weight': 0.5},
 {'cost': '5 gp', 'name': "Scale, merchant's", 'props': {}, 'weight': 3},
 {'cost': '5 sp', 'name': 'Sealing wax', 'props': {}, 'weight': 0},
 {'cost': '2 gp', 'name': 'Shovel', 'props': {}, 'weight': 5},
 {'cost': '5 cp', 'name': 'Signal whistle', 'props': {}, 'weight': 0},
 {'cost': '5 gp', 'name': 'Signet ring', 'props': {}, 'weight': 0},
 {'cost': '0 cp', 'name': 'Small knife', 'props': {}, 'weight': 0},
 {'cost': '2 cp', 'name': 'Soap', 'props': {}, 'weight': 0},
 {'cost': '50 gp', 'name': 'Spellbook', 'props': {}, 'weight': 3},
 {'cost': '1 sp', 'name': 'Spike, iron', 'props': {}, 'weight': 5},
 {'cost': '1000 gp', 'name': 'Spyglass', 'props': {}, 'weight': 1},
 {'cost': '0 cp', 'name': 'String (10 feet)', 'props': {}, 'weight': 0},
 {'cost': '2 gp', 'name': 'Tent, two-person', 'props': {}, 'weight': 20},
 {'cost': '5 sp', 'name': 'Tinderbox', 'props': {}, 'weight': 1},
 {'cost': '1 cp', 'name': 'Torch', 'props': {}, 'weight': 1},
 {'cost': '0 cp', 'name': 'Vestments', 'props': {}, 'weight': 0},
 {'cost': '1 gp', 'name': 'Vial', 'props': {}, 'weight': 0},
 {'cost': '2 sp', 'name': 'Waterskin', 'props': {}, 'weight': 5},
 {'cost': '1 cp', 'name': 'Whetstone', 'props': {}, 'weight': 1},
 {'cost': '16 gp', 'name': "Burglar's Pack", 'props': {}, 'weight': None},
 {'cost': '39 gp', 'name': "Diplomat's Pack", 'props': {}, 'weight': None},
 {'cost': '12 gp', 'name': "Dungeoneer's Pack", 'props': {}, 'weight': None},
 {'cost': '40 gp', 'name': "Entertainer's Pack", 'props': {}, 'weight': None},
 {'cost': '10 gp', 'name': "Explorer's Pack", 'props': {}, 'weight': None},
 {'cost': '19 gp', 'name': "Priest's Pack", 'props': {}, 'weight': None},
 {'cost': '40 gp', 'name': "Scholar's Pack", 'props': {}, 'weight': None},
 {'cost': '50 gp', 'name': "Alchemist's Supplies", 'props': {}, 'weight': 8},
 {'cost': '20 gp', 'name': "Brewer's Supplies", 'props': {}, 'weight': 9},
 {'cost': '10 gp', 'name': "Calligrapher's Supplies", 'props': {}, 'weight': 5},
 {'cost': '8 gp', 'name': "Carpenter's Tools", 'props': {}, 'weight': 6},
 {'cost': '15 gp', 'name': "Cartographer's Tools", 'props': {}, 'weight': 6},
 {'cost': '5 gp', 'name': "Cobbler's Tools", 'props': {}, 'weight': 5},
 {'cost': '1 gp', 'name': "Cook's utensils", 'props': {}, 'weight': 8},
 {'cost': '30 gp', 'name': "Glassblower's Tools", 'props': {}, 'weight': 5},
 {'cost': '25 gp', 'name': "Jeweler's Tools", 'props': {}, 'weight': 2},
 {'cost': '5 gp', 'name': "Leatherworker's Tools", 'props': {}, 'weight': 5},
 {'cost': '10 gp', 'name': "Mason's Tools", 'props': {}, 'weight': 8},
 {'cost': '10 gp', 'name': "Painter's Supplies", 'props': {}, 'weight': 5},
 {'cost': '10 gp', 'name': "Potter's Tools", 'props': {}, 'weight': 3},
 {'cost': '20 gp', 'name': "Smith's Tools", 'props': {}, 'weight': 8},
 {'cost': '50 gp', 'name': "Tinker's Tools", 'props': {}, 'weight': 10},
 {'cost': '1 gp', 'name': "Weaver's Tools", 'props': {}, 'weight': 5},
 {'cost': '1 gp', 'name': "Woodcarver's Tools", 'props': {}, 'weight': 5},
 {'cost': '1 sp', 'name': 'Dice Set', 'props': {}, 'weight': 0},
 {'cost': '5 sp', 'name': 'Playing Card Set', 'props': {}, 'weight': 0},
 {'cost': '30 gp', 'name': 'Bagpipes', 'props': {}, 'weight': 6},
 {'cost': '6 gp', 'name': 'Drum', 'props': {}, 'weight': 3},
 {'cost': '25 gp', 'name': 'Dulcimer', 'props': {}, 'weight': 10},
 {'cost': '2 gp', 'name': 'Flute', 'props': {}, 'weight': 1},
 {'cost': '35 gp', 'name': 'Lute', 'props': {}, 'weight': 2},
 {'cost': '30 gp', 'name': 'Lyre', 'props': {}, 'weight': 2},
 {'cost': '3 gp', 'name': 'Horn', 'props': {}, 'weight': 2},
 {'cost': '12 gp', 'name': 'Pan flute', 'props': {}, 'weight': 2},
 {'cost': '2 gp', 'name': 'Shawm', 'props': {}, 'weight': 1},
 {'cost': '30 gp', 'name': 'Viol', 'props': {}, 'weight': 1},
 {'cost': '25 gp', 'name': "Navigator's Tools", 'props': {}, 'weight': 2},
 {'cost': '25 gp', 'name': "Thieves' Tools", 'props': {}, 'weight': 1},
 {'cost': '50 gp', 'name': 'Camel', 'props': {}, 'weight': None},
 {'cost': '8 gp', 'name': 'Donkey', 'props': {}, 'weight': None},
 {'cost': '8 gp', 'name': 'Mule', 'props': {}, 'weight': None},
 {'cost': '200 gp', 'name': 'Elephant', 'props': {}, 'weight': None},
 {'cost': '50 gp', 'name': 'Horse, draft', 'props': {}, 'weight': None},
 {'cost': '75 gp', 'name': 'Horse, riding', 'props': {}, 'weight': None},
 {'cost': '25 gp', 'name': 'Mastiff', 'props': {}, 'weight': None},
 {'cost': '30 gp', 'name': 'Pony', 'props': {}, 'weight': None},
 {'cost': '400 gp', 'name': 'Warhorse', 'props': {}, 'weight': None},
 {'cost': '20 gp', 'name': 'Barding: Padded', 'props': {}, 'weight': 16},
 {'cost': '40 gp', 'name': 'Barding: Leather', 'props': {}, 'weight': 20},
 {'cost': '180 gp', 'name': 'Barding: Studded Leather', 'props': {}, 'weight': 26},
 {'cost': '40 gp', 'name': 'Barding: Hide', 'props': {}, 'weight': 24},
 {'cost': '200 gp', 'name': 'Barding: Chain shirt', 'props': {}, 'weight': 40},
 {'cost': '200 gp', 'name': 'Barding: Scale mail', 'props': {}, 'weight': 90},
 {'cost': '1600 gp', 'name': 'Barding: Breastplate', 'props': {}, 'weight': 40},
 {'cost': '3000 gp', 'name': 'Barding: Half plate', 'props': {}, 'weight': 80},
 {'cost': '12 gp', 'name': 'Barding: Ring mail', 'props': {}, 'weight': 80},
 {'cost': '300 gp', 'name': 'Barding: Chain mail', 'props': {}, 'weight': 110},
 {'cost': '800 gp', 'name': 'Barding: Splint', 'props': {}, 'weight': 120},
 {'cost': '6000 gp', 'name': 'Barding: Plate', 'props': {}, 'weight': 130},
 {'cost': '2 gp', 'name': 'Bit and bridle', 'props': {}, 'weight': 1},
 {'cost': '100 gp', 'name': 'Carriage', 'props': {}, 'weight': 600},
 {'cost': '15 gp', 'name': 'Cart', 'props': {}, 'weight': 200},
 {'cost': '250 gp', 'name': 'Chariot', 'props': {}, 'weight': 100},
 {'cost': '5 cp', 'name': 'Animal Feed (1 day)', 'props': {}, 'weight': 10},
 {'cost': '60 gp', 'name': 'Saddle, Exotic', 'props': {}, 'weight': 50},
 {'cost': '20 gp', 'name': 'Saddle, Military', 'props': {}, 'weight': 30},
 {'cost': '5 gp', 'name': 'Saddle, Pack', 'props': {}, 'weight': 15},
 {'cost': '10 gp', 'name': 'Saddle, Riding', 'props': {}, 'weight': 25},
 {'cost': '4 gp', 'name': 'Saddlebags', 'props': {}, 'weight': 8},
 {'cost': '20 gp', 'name': 'Sled', 'props': {}, 'weight': 300},
 {'cost': '5 sp', 'name': 'Stabling (1 day)', 'props': {}, 'weight': 0},
 {'cost': '35 gp', 'name': 'Wagon', 'props': {}, 'weight': 400},
 {'cost': '30000 gp', 'name': 'Galley', 'props': {}, 'weight': None},
 {'cost': '3000 gp', 'name': 'Keelboat', 'props': {}, 'weight': None},
 {'cost': '10000 gp', 'name': 'Longship', 'props': {}, 'weight': None},
 {'cost': '50 gp', 'name': 'Rowboat', 'props': {}, 'weight': None},
 {'cost': '10000 gp', 'name': 'Sailing ship', 'props': {}, 'weight': None},
 {'cost': '25000 gp', 'name': 'Warship', 'props': {}, 'weight': None}]

ITEMS = WEAPONS + ARMOR + SHIELDS + GEAR
